version: '3.9'

x-ns-common-env: &ns-common-env
  NODE_ENV: production
  TZ: Europe/Oslo
  TIMEZONE: Europe/Oslo
  TIME_FORMAT: 24
  INSECURE_USE_HTTP: 'true'
  ALARM_HIGH: off 
  ALARM_LOW: off 
  ALARM_TIMEAGO_URGENT: off 
  ALARM_TIMEAGO_WARN: off 
  ALARM_TYPES: predict 
  ALARM_URGENT_HIGH: off 
  ALARM_URGENT_LOW: off
  AUTH_DEFAULT_ROLES: denied 
  BASAL_RENDER: icicle 
  BG_HIGH: 14 
  BG_LOW: 3.7 
  BG_TARGET_BOTTOM: 3.9 
  BG_TARGET_TOP: 10 
  BOLUS_RENDER_FORMAT: default 
  BOLUS_RENDER_FORMAT_SMALL: minimal 
  BOLUS_RENDER_OVER: 0.5 
  BRIDGE_INTERVAL: 120000 
  BRIDGE_SERVER: EU
  CORS_ALLOW_ORIGIN: https://nightscout-reporter.zreptil.de 
  DEVICESTATUS_ADVANCED: true 
  DEVICESTATUS_DAYS: 1 
  DISABLE: treatmentnotify 
  DISPLAY_UNITS: mmol 
  ENABLE: pump iob cob basal careportal sage cage override cors bwp boluscalc maker openaps bridge loop 
  FRAME_URL_1: 
  FRAME_URL_2: 
  LANGUAGE: nb 
  LOOP_ENABLE_ALERTS: 'false' 
  LOOP_URGENT: 30 
  LOOP_WARN: 16 
  OPENAPS_COLOR_PREDICTION_LINES: 'true' 
  OPENAPS_ENABLE_ALERTS: 'false' 
  OPENAPS_FIELDS: status-symbol status-label iob meal-assist rssi 
  OPENAPS_PRED_COB_COLOR: #f5d549 
  OPENAPS_PRED_UAM_COLOR: #ff5500 
  OPENAPS_RETRO_FIELDS: status-symbol status-label iob meal-assist rssi 
  OPENAPS_URGENT: 27 
  OPENAPS_WARN: 7 
  PUMP_FIELDS: battery reservoir clock status 
  PUMP_RETRO_FIELDS: battery reservoir clock status 
  SAGE_INFO: 192 
  SAGE_URGENT: 238 
  SAGE_WARN: 210 
  SCALE_Y: linear 
  SHOW_CLOCK_DELTA: 'true' 
  SHOW_CLOCK_LAST_TIME: 'true' 
  SHOW_FORECAST: openaps 
  SHOW_PLUGINS: iob cob careportal basal override boluscalc sage cage openaps 
  THEME: colors  
   

services:
  mongo:
    image: mongo:4.4
    restart: always
    container_name: mongo
    volumes:
      - ${NS_MONGO_DATA_DIR:-./mongo-data}:/data/db:cached

  nightscout-${NS_SUBDOMAIN}:
    image: bjornoleh/nightscout:latest
    container_name: nightscout-${NS_SUBDOMAIN}
    restart: always
    depends_on:
      - mongo
    labels:
      - 'traefik.enable=true'
      # Change the below Host from `localhost` to be the web address where Nightscout is running.
      # Also change the email address in the `traefik` service below.
      - 'traefik.http.routers.nightscout.${NS_SUBDOMAIN}.rule=Host(`${NS_SUBDOMAIN}.${NS_DOMAIN}`)'
      - 'traefik.http.routers.nightscout.${NS_SUBDOMAIN}.entrypoints=websecure'
      - 'traefik.http.routers.nightscout.${NS_SUBDOMAIN}.tls.certresolver=le'
    environment:
      ### Variables for the container
      <<: *ns-common-env
      CUSTOM_TITLE:
      API_SECRET: ${NS_SECRET}
      BRIDGE_USER_NAME:
      BRIDGE_PASSWORD:
      MONGO_CONNECTION: mongodb://mongo:27017/ns-${NS_SUBDOMAIN}

  traefik:
    image: traefik:latest
    container_name: 'traefik'
    restart: always
    command:
      - '--providers.docker=true'
      - '--providers.docker.exposedbydefault=false'
      - '--entrypoints.web.address=:80'
      - '--entrypoints.web.http.redirections.entrypoint.to=websecure'
      - '--entrypoints.websecure.address=:443'
      - "--certificatesresolvers.le.acme.httpchallenge=true"
      - "--certificatesresolvers.le.acme.httpchallenge.entrypoint=web"
      - '--certificatesresolvers.le.acme.storage=/letsencrypt/acme.json'
      # Change the below to match your email address
      - '--certificatesresolvers.le.acme.email=${NS_EMAIL}'
    ports:
      - '443:443'
      - '80:80'
    volumes:
      - './letsencrypt:/letsencrypt'
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
