version: '3.9'

x-ns-common-env: &ns-common-env
  NODE_ENV: production
  TZ: Europe/Oslo
  TIMEZONE: Europe/Oslo
  TIME_FORMAT: 24
  INSECURE_USE_HTTP: 'false'
  DEVICESTATUS_ADVANCED: 'true'
  DISPLAY_UNITS: mmol
  LANGUAGE:
  OPENAPS_COLOR_PREDICTION_LINES: 'true'
  PUMP_FIELDS: clock reservoir
  SHOW_FORECAST: openaps
  THEME: colors

x-logging:
  &default-logging
  options:
    max-size: '10m'
    max-file: '5'
  driver: json-file

services:
  mongo:
    image: mongo:4.4
    restart: always
    container_name: mongo
    volumes:
      - ${NS_MONGO_DATA_DIR:-./mongo-data}:/data/db:cached
    ports:
      - "27017"
    logging: *default-logging

  traefik:
    image: traefik:latest
    container_name: 'traefik'
    restart: always
    command:
      - '--providers.docker=true'
      - '--providers.docker.exposedbydefault=false'
      - '--entrypoints.web.address=:80'
      - '--entrypoints.web.http.redirections.entrypoint.to=websecure'
      - '--entrypoints.websecure.address=:443'
      - "--certificatesresolvers.le.acme.httpchallenge=true"
      - "--certificatesresolvers.le.acme.httpchallenge.entrypoint=web"
      - '--certificatesresolvers.le.acme.storage=/letsencrypt/acme.json'
      - '--certificatesresolvers.le.acme.email=${NS_EMAIL}'
    ports:
      - '443:443'
      - '80:80'
    volumes:
      - './letsencrypt:/letsencrypt'
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
    logging: *default-logging
